package repository;

import domain.Client;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import static connection.DatabaseConnection.getConnection;

public class ClientDAOImpl implements ClientDAO {

    /**
     * Retrieves all clients from the database ordered by client_id.
     *
     * @return a List of Client objects; empty if no clients found
     * @throws SQLException if a database access error occurs
     */
    @Override
    public List<Client> listClients() {
        List<Client> clients = new ArrayList<>();
        PreparedStatement preparedStatement;
        ResultSet resultSet;

        try (Connection dbConnection = getConnection()) {
            try {
                String selectClientsQuery = "SELECT * FROM client ORDER BY client_id";
                preparedStatement = dbConnection.prepareStatement(selectClientsQuery);
                resultSet = preparedStatement.executeQuery();

                while (resultSet.next()) {
                    Client client = new Client();
                    client.setClientId(resultSet.getInt("client_id"));
                    client.setClientName(resultSet.getString("client_name"));
                    client.setClientSecondName(resultSet.getString("client_second_name"));
                    client.setMembership(resultSet.getInt("membership"));

                    clients.add(client);
                }

            } catch (SQLException s) {
                System.out.println("Failed to list clients: " + s.getMessage());
            }
        } catch (SQLException e) {
            System.out.println("Failed to close database connection: " + e.getMessage());
        }

        return clients;
    }

    /**
     * Finds a client in the database by its ID.
     * <p>
     * If the client exists, this method updates the given {@link Client}
     * object with data from the database and returns {@code true}.
     * Otherwise, it returns {@code false}.
     * </p>
     *
     * @param client the {@link Client} with the ID to search for
     * @return {@code true} if the client was found, {@code false} otherwise
     */
    @Override
    public boolean findClientById(Client client) {
        PreparedStatement preparedStatement;
        ResultSet resultSet;

        try (Connection dbConnection = getConnection()) {
            try {
                String findClientIdQuery = "SELECT * FROM client WHERE client_id = ?";
                preparedStatement = dbConnection.prepareStatement(findClientIdQuery);
                preparedStatement.setInt(1, client.getClientId());
                resultSet = preparedStatement.executeQuery();

                if (resultSet.next()) {
                    client.setClientName(resultSet.getString("client_name"));
                    client.setClientSecondName(resultSet.getString("client_second_name"));
                    client.setMembership(resultSet.getInt("membership"));
                    return true;
                }

            } catch (SQLException e) {
                System.out.println("Failed to find a client by his id: " + e.getMessage());
            }
        } catch (SQLException e) {
            System.out.println("Failed to close the DB connection: " + e.getMessage());
        }
        return false;
    }

    /**
     * Adds a new client to the database.
     * <p>
     * This method inserts the data from the provided {@link Client} object
     * into the "client" table. Only the client's name, second name, and
     * membership are stored; the ID is assumed to be auto-generated by the database.
     * </p>
     *
     * @param client the {@link Client} object containing the data to insert
     * @return {@code true} if the client was successfully added, {@code false} otherwise
     */

    @Override
    public boolean addClient(Client client) {
        PreparedStatement preparedStatement;
        Connection connection = getConnection();

        String addClientQuery = "INSERT INTO client(client_name, client_second_name, membership)"
                + "VALUES(?, ?, ?)";

        try {
            preparedStatement = connection.prepareStatement(addClientQuery);
            preparedStatement.setString(1, client.getClientName());
            preparedStatement.setString(2, client.getClientSecondName());
            preparedStatement.setInt(3, client.getMembership());
            preparedStatement.executeQuery();
            return true;
        } catch (SQLException e){
            System.out.println("Failed to add client: " + e.getMessage());
        } finally {
            try {
                connection.close();
            } catch (Exception e){
                System.out.println("Failed to close the DB connection: " + e.getMessage());
            }
        }
        return false;
    }

    /**
     * Updates an existing client's information in the database.
     * <p>
     * The method updates the name, second name, and membership of the client
     * identified by its ID in the "client" table. The {@link Client} object
     * must have a valid ID corresponding to an existing record.
     * </p>
     *
     * @param client the {@link Client} object containing updated data and the ID
     * @return {@code true} if the update was successful, {@code false} otherwise
     */
    @Override
    public boolean updateClient(Client client) {
        PreparedStatement preparedStatement;
        Connection connection = getConnection();

        String updateClientQuery = "UPDATE client SET client_name = ?, client_second_name = ?, membership = ?"
                + "WHERE client_id = ?";
        try {
            preparedStatement = connection.prepareStatement(updateClientQuery);
            preparedStatement.setString(1, client.getClientName());
            preparedStatement.setString(2, client.getClientSecondName());
            preparedStatement.setInt(3, client.getMembership());
            preparedStatement.setInt(4, client.getClientId());
            preparedStatement.executeQuery();
            return true;
        } catch (SQLException e){
            System.out.println("Failed to update client: " +e.getMessage());
        } finally {
            try {
                connection.close();
            } catch (Exception e){
                System.out.println("Failed to close the DB connection: " + e.getMessage());
            }
        }
        return false;
    }

    /**
     * Deletes a client from the database based on its ID.
     * <p>
     * The method removes the record from the "client" table corresponding
     * to the ID of the provided {@link Client} object.
     * </p>
     *
     * @param client the {@link Client} object containing the ID of the client to delete
     * @return {@code true} if the deletion was successful, {@code false} otherwise
     */
    @Override
    public boolean deleteClient(Client client) {
        PreparedStatement preparedStatement;
        Connection connection = getConnection();

        String updateClientQuery = "DELETE FROM client WHERE client_id = ?";

        try {
            preparedStatement = connection.prepareStatement(updateClientQuery);
            preparedStatement.setInt(1, client.getClientId());
            preparedStatement.executeQuery();
            return true;
        } catch (SQLException e){
            System.out.println("Failed to delete a client: " +e.getMessage());
        } finally {
            try {
                connection.close();
            } catch (Exception e){
                System.out.println("Failed to close the DB connection" + e.getMessage());
            }
        }
        return false;
    }

}
